name: 'cargopulse'
version: '1.0.0'
config-version: 2

profile: 'cargopulse'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cargopulse:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    analytics:
      +materialized: table

    risk:
      +materialized: table
