services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: cargopulse-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cargopulse
      POSTGRES_USER: cargopulse
      POSTGRES_PASSWORD: cargopulse_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cargopulse -d cargopulse"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
